version: 2
jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install flask
      - run: pip install flask_session
      - run: pip install flask_mysqldb
      - run: pip install MySQLdb.cursors
      - run: pip install re
      - run: python -m unittest discover -v
workflows:
  build-and-test:
    jobs:
      - test
